steps:
  - id: yarn-install
    waitFor: ["-"]
    name: node:12.15
    env:
      - PUPPETEER_SKIP_DOWNLOAD=true
    args: ["yarn"]

  - id: download-chrome
    waitFor: ["-"]
    name: node:12.15
    args:
      [
        "curl",
        "https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/737027/chrome-linux.zip",
        "-o",
        "chrome-linux.zip",
      ]

  - id: puppeteer-install
    waitFor: ["yarn-install"]
    name: node:12.15
    env:
      - DEBUG=*
    args: ["node", "install.js"]
