steps:
  - id: yarn-install
    waitFor: ["-"]
    name: node:12.15
    args: ["yarn"]

  - id: rm-chrome
    waitFor: ["yarn-install"]
    name: node:12.15
    args: ["rm", "-rf", "/workspace/.local-chromium/linux-737027"]

  - id: puppeteer-install
    waitFor: ["rm-chrome"]
    name: node:12.15
    env:
      - DEBUG=*
    args: ["node", "install.js"]
